#!/bin/sh
set -eu

## Utilities {{{
cmdpath() { command -v "${1}"; }
iscmd()   { cmdpath "${1}" >/dev/null 2>&1; }

# Print command if dry run, execute otherwise
execcmd() {
    if [ "${DRY_RUN}" = "1" ]; then
        printf "%s\n" "$*"
    else
        "$@"
    fi
}
## }}}

## Preparation {{{
# Ensure commands
ALL_CMD_FOUND="1"
for CMD in s6-svscan s6-envdir s6-rc-init s6-rc-compile s6-rc-update s6-clock s6-rc abduco; do
    iscmd "${CMD}" || {
        ALL_CMD_FOUND="0"
        printf "Command not found: %s\n" "${CMD}"
    }
done
[ "${ALL_CMD_FOUND}" = "1" ] || exit 1

# Get absolute command paths (in case of local installation / idk if needed)
    S6_SVSCAN_BIN="$(cmdpath "s6-svscan")"
    S6_ENVDIR_BIN="$(cmdpath "s6-envdir")"
   S6_RC_INIT_BIN="$(cmdpath "s6-rc-init")"
S6_RC_COMPILE_BIN="$(cmdpath "s6-rc-compile")"
 S6_RC_UPDATE_BIN="$(cmdpath "s6-rc-update")"
     S6_CLOCK_BIN="$(cmdpath "s6-clock")"
        S6_RC_BIN="$(cmdpath "s6-rc")"
       ABDUCO_BIN="$(cmdpath "abduco")"
## }}}

# Run svscan on service dir
s6_init() {
    local SVC_DIR="${1}"
    local LOGFILE="${2}"
    local ENV_DIR="${3}"

    # Ensure service dir
    execcmd install -d -o "${USER}" -g "${USER}" -m 750 "${SVC_DIR}"

    # Run s6-svscan in abduco if not already running
    if ! { "${ABDUCO_BIN}" | tail +2 | sed 's/.*\t//' | grep "^s6-svscan$" >/dev/null 2>&1; }; then
        execcmd "${ABDUCO_BIN}" -n s6-svscan \
            sh -c '"${1}" -I "${2}"  "${3}" "${4}" 2>&1 | tee "${5}"' '' \
            "${S6_ENVDIR_BIN}" "${ENV_DIR}" \
            "${S6_SVSCAN_BIN}" "${SVC_DIR}" \
            "${LOGFILE}"
    else
        printf "[I]: s6-svscan already running!\n"
    fi
}

# Initialize s6-rc state
s6rc_init() {
    execcmd "${S6_RC_INIT_BIN}" -c "${S6_RC_DB_DIR}/compiled" -l "${S6_RC_LIVE_DIR}" "${S6_SERVICE_DIR}"
}

# Compile service dir to db
s6rc_compile_db() {
    local COMPILED_DB="${S6_RC_DB_DIR}/compiled-$("${S6_CLOCK_BIN}")"
    execcmd "${S6_RC_COMPILE_BIN}" -v2 "${COMPILED_DB}" "${S6_RC_SV_DIR}"
}

# Fetch name of newest db
s6rc_newest_db() {
    find "${S6_RC_DB_DIR}" -maxdepth 1 -type d -name compiled\* \
        | sort | tail -1
}

# Update live db to the newest one
s6rc_update_live_db() {
    local NEW_DB="$(s6rc_newest_db)"
    execcmd "${S6_RC_UPDATE_BIN}" -v2 -l "${S6_RC_LIVE_DIR}" "${NEW_DB}"

    # Atomic symlink update
    execcmd ln -sf "${NEW_DB##*/}" "${S6_RC_DB_DIR}/compiled/compiled"
    execcmd mv -f "${S6_RC_DB_DIR}/compiled/compiled" "${S6_RC_DB_DIR}/"
}

s6rc_list_up() {
    "${S6_RC_BIN}" -l "${S6_RC_LIVE_DIR}" -a list
}

s6rc_list_down() {
    "${S6_RC_BIN}" -l "${S6_RC_LIVE_DIR}" -ad list
}

usage() {
    printf "%s [options] command\n" "${0}"
    printf "\n"
    printf "  options:\n"
    printf "    -n                dry run\n"
    printf "\n"
    printf "  commands:\n"
    printf "    init_s6           Runs s6-svscan in abduco\n"
    printf "    init_s6-rc        Initializes s6-rc state\n"
    printf "    compile_db        Compiles a new db from the service definitions\n"
    printf "    update_live_db    Updates the db that s6-rc is using to the newest one\n"
    printf "    svc_list_up       List active services\n"
    printf "    svc_list_down     List inactive services\n"
}

## Variables {{{
_USER="$(id -u -n)"
 _UID="$(id -u)"
_HOME="$(homeof "${_USER}")"
_TMPDIR="${TMPDIR:-/tmp}"

var_gen_s6_service_dir() {
    [ "${_UID}" = "0" ] \
        && printf "/run/service" \
        || printf "${_TMPDIR}/s6-service-${_UID}"
}

var_gen_s6_rc_live_dir() {
    [ "${_UID}" = "0" ] \
        && printf "/run/s6-rc" \
        || printf "${_TMPDIR}/s6-rc-${_UID}"
}

var_gen_s6_env_dir() {
    [ "${_UID}" = "0" ] \
        && printf "/etc/s6/env.d" \
        || printf "${_HOME}/.local/share/s6/env.d"
}

var_gen_s6_rc_sv_dir() {
    [ "${_UID}" = "0" ] \
        && printf "/etc/s6/sv" \
        || printf "${_HOME}/.local/share/s6/sv"
}

var_gen_s6_rc_db_dir() {
    [ "${_UID}" = "0" ] \
        && printf "/etc/s6/rc" \
        || printf "${_HOME}/.local/share/s6/rc"
}

var_gen_s6_logfile() {
    [ "${_UID}" = "0" ] \
        && printf "/var/log/s6.log" \
        || printf "/tmp/s6-${_UID}.log"
}
## }}}

## Commands {{{

cmd_init() {
    [ -n "${OPT_S}" ] || OPT_S="$(var_gen_s6_service_dir)"

    if [ "${1}" = "s6" ]; then
        [ -n "${OPT_L}" ] || OPT_L="$(var_gen_s6_logfile)"
        [ -n "${OPT_E}" ] || OPT_E="$(var_gen_s6_env_dir)"

        s6_init "${OPT_S}" "${OPT_L}" "${OPT_E}"
    elif [ "${1}" = "s6-rc" ]; then
        # TODO

        exit 1
    else
        exit 1
    fi
}

cmd_compile_db() {
    exit 1
}

cmd_switch_live_db() {
    exit 1
}

cmd_update_db() {
    exit 1
}

cmd_sv() {
    exit 1
}

cmd_rc() {
    exit 1
}

## }}}

## MAIN {{{

# Check if any args present
[ "${#}" -gt 0 ] || { usage; exit 0; }

# Default options
DRY_RUN="1"
OPT_D=""
OPT_E=""
OPT_L=""
OPT_S=""

# Parse option args
while [ "${#}" -gt 0 ]; do
    case "${1}" in

        "-n") DRY_RUN="1"
              shift 1
              ;;

        "-d") [ "${#}" -ge 2 ] || exit 1
              OPT_D="${2}"
              shift 2
              ;;

        "-e") [ "${#}" -ge 2 ] || exit 1
              OPT_E="${2}"
              shift 2
              ;;

        "-l") [ "${#}" -ge 2 ] || exit 1
              OPT_L="${2}"
              shift 2
              ;;

        "-s") [ "${#}" -ge 2 ] || exit 1
              OPT_S="${2}"
              shift 2
              ;;

           *) break ;;
    esac
done

# Check if any command specified
[ "${#}" -gt 0 ] || { usage; exit 1; }

# Decide what to do
CMDNAME="${1}"
if iscmd "cmd_${CMDNAME}"; then
    shift 1
    "cmd_${CMDNAME}" "$@"
else
    usage
    exit 1
fi

## }}}
